unit TestUIControlTypeStyleRegistry;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, SysUtils, Classes, UIControlTypeStyleRegistry, TypeObjectRegistry,
  UIControlStyle, UIStandardControlStyle;
type
  // Test methods for class TUIControlTypeStyleRegistry
  
  TestTUIControlTypeStyleRegistry = class(TTestCase)
  strict private
    FUIControlTypeStyleRegistry: TUIControlTypeStyleRegistry;
  public
    procedure SetUp; override;
    procedure TearDown; override;

  published

    procedure TestRegisterUIControlTypeStyle;

  published

    procedure TestGetUIControlTypeStyle_AllowStyleUsingByControlTypeInheritanceDisabled;
    procedure TestGetUIControlTypeStyle_AllowStyleUsingByControlTypeInheritanceEnabled;

  published

    procedure TestUnregisterUIControlTypeStyle;
    
  end;

implementation

uses

  cxButtons,
  Controls,
  StdCtrls;
  
procedure TestTUIControlTypeStyleRegistry.SetUp;
begin
  FUIControlTypeStyleRegistry := TUIControlTypeStyleRegistry.Create;
end;

procedure TestTUIControlTypeStyleRegistry.TearDown;
begin
  FUIControlTypeStyleRegistry.Free;
  FUIControlTypeStyleRegistry := nil;
end;

procedure TestTUIControlTypeStyleRegistry.
  TestGetUIControlTypeStyle_AllowStyleUsingByControlTypeInheritanceDisabled;
var Style: IUIControlStyle;
begin

  Style := TUIButtonStyle.Create;
  
  FUIControlTypeStyleRegistry.
    RegisterOrUpdateUIControlTypeStyle(
      TButton, Style, DisallowStyleUsingByControlTypeInheritance
    );

  CheckSame(FUIControlTypeStyleRegistry.GetUIControlTypeStyle(TcxButton), nil);

end;

procedure TestTUIControlTypeStyleRegistry.
  TestGetUIControlTypeStyle_AllowStyleUsingByControlTypeInheritanceEnabled;
var Style: IUIControlStyle;
begin

  Style := TUIButtonStyle.Create;
  
  FUIControlTypeStyleRegistry
    .RegisterOrUpdateUIControlTypeStyle(
      TButton, Style, AllowStyleUsingByControlTypeInheritance
    );

  CheckSame(FUIControlTypeStyleRegistry.GetUIControlTypeStyle(TcxButton), Style);
  CheckSame(FUIControlTypeStyleRegistry.GetUIControlTypeStyle(TButton), Style);
  
end;

procedure TestTUIControlTypeStyleRegistry.
  TestRegisterUIControlTypeStyle;
var Style: IUIControlStyle;
begin

  Style := TUIButtonStyle.Create;
  
  FUIControlTypeStyleRegistry.RegisterOrUpdateUIControlTypeStyle(TButton, Style);

  CheckSame(FUIControlTypeStyleRegistry.GetUIControlTypeStyle(TButton), Style);

end;

procedure TestTUIControlTypeStyleRegistry.TestUnregisterUIControlTypeStyle;
var Style: IUIControlStyle;
begin

  Style := TUIButtonStyle.Create;

  FUIControlTypeStyleRegistry.RegisterOrUpdateUIControlTypeStyle(TButton, Style);

  FUIControlTypeStyleRegistry.UnregisterUIControlTypeStyle(TButton);

  CheckSame(FUIControlTypeStyleRegistry.GetUIControlTypeStyle(TButton), nil);
  
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTUIControlTypeStyleRegistry.Suite);
end.

